### ISSUE TITLE
更新一下不  挖矿  沾福气  免费第一次抽奖

### ISSUE THREAD

**Issue by fadeds** [charmingYouYou/juejin_sign_ql#1]

**Comment by charmingYouYou** [comment]
免费第一次抽奖是有的, 沾福气我这两天抽空加下, 挖矿没了解过, 我得看看有没现成的代码

**Comment by fadeds** [comment]
https://github.com/fadeds/juejin-auto-checkin

**Comment by fadeds** [comment]
这里面

**Comment by charmingYouYou** [comment]
> 这里面

ok, 临放假前我抽空搞一下~

**Comment by charmingYouYou** [comment]
> _No description provided._

更新了挖矿和沾福气, 可以更新下试试, 挖矿我自测没问题, 沾福气今天跑过了, 还没试

**Comment by fadeds** [comment]
好的

**Comment by charmingYouYou** [comment]
> 好的

更新的命令变了, 最好按照文档再走一遍

**Comment by fadeds** [comment]
![image](https://user-images.githubusercontent.com/27796945/150947010-91e60025-92da-4b56-a4f9-5f76b39b1525.png)
没拉下来

**Comment by charmingYouYou** [comment]
> ![image](https://user-images.githubusercontent.com/27796945/150947010-91e60025-92da-4b56-a4f9-5f76b39b1525.png) 没拉下来

手动运行一下, 如果还要问题, 发下日志

**Comment by fadeds** [comment]
![image](https://user-images.githubusercontent.com/27796945/150947530-b73e9801-9935-4ff0-80c3-6ec67b738178.png)

**Comment by fadeds** [comment]
你可以把脚本删了  拉一下

**Comment by charmingYouYou** [comment]
> 你可以把脚本删了 拉一下

我删了重新拉了, 是正常的, 你看看你青龙版本, 我用的2.11.1最新的
![image](https://user-images.githubusercontent.com/31199453/150948129-fddc6391-e55e-429f-b342-1e38af686655.png)

**Comment by fadeds** [comment]
我也是  我用的脚本库里面的脚本  跟任务名也有关系吗？

**Comment by fadeds** [comment]
![image](https://user-images.githubusercontent.com/27796945/150948417-44ef9415-4ef5-40f7-968b-72ab09983d87.png)
还是一样

**Comment by charmingYouYou** [comment]
> 我也是 我用的脚本库里面的脚本 跟任务名也有关系吗？

你这样, 你把加入的定时任务删了, 进docker把青龙下scripts 对应的脚本目录删除再执行一次
![image](https://user-images.githubusercontent.com/31199453/150948578-6ec3d50b-e2f2-4052-91e9-0b996f92ec07.png)

**Comment by fadeds** [comment]
删掉了  还是不行  
![330da01923893644cf786a4d4dcfade](https://user-images.githubusercontent.com/27796945/151087328-4883cab2-236e-478f-85fa-8c291b8eaef6.png)
我的目录下面没有main

**Comment by fadeds** [comment]
ql repo https://github.com.cnpmjs.org/charmingYouYou/juejin_sign_ql.git "juejin" "icon" "game|autoGame"    没有加代理  就需要加cnpmjs.org   不然拉不下来

**Comment by charmingYouYou** [comment]
> ql repo https://github.com.cnpmjs.org/charmingYouYou/juejin_sign_ql.git "juejin" "icon" "game|autoGame" 没有加代理 就需要加cnpmjs.org 不然拉不下来

换了域名现在脚本已经正常拉取了吧? 我更新下文档吧, 功能今早自动跑了都是没问题的

**Comment by fadeds** [comment]
脚本没问题  就是青龙2.11.1的代理去掉了  就拉不下来了  需要加代理  或者改路径，我加的代理有问题  也删掉了  用的cnpmjs.org

**Comment by charmingYouYou** [comment]
> 脚本没问题 就是青龙2.11.1的代理去掉了 就拉不下来了 需要加代理 或者改路径，我加的代理有问题 也删掉了 用的cnpmjs.org

更新了个gitee源, 拉取就没问题了
