### ISSUE TITLE
多账号

### ISSUE THREAD

**Issue by TOMhongshu** [charmingYouYou/juejin_sign_ql#7]
什么时候更新一下支持多账号

**Comment by charmingYouYou** [comment]
更新支持了, 再看下文档配置下吧

**Comment by TOMhongshu** [comment]
多账号是一个账号一行吗比如
JUEJIN_INFO="cookie1|=|userId1"
JUEJIN_INFO="cookie2|=|userId2"
JUEJIN_INFO="cookie3|=|userId3"

**Comment by charmingYouYou** [comment]
对, 不过是在青龙添加多个同名JUEJIN_INFO环境变量

**Comment by charmingYouYou** [comment]
你可以添加完测试一下看下日志

**Comment by TOMhongshu** [comment]
我的日志都是乱码但是企业微信的通知是正常的
图片：https://s3.bmp.ovh/imgs/2022/05/14/821e0f919e91daa1.png

**Comment by charmingYouYou** [comment]
这是因为你今天已经签到过了, 你明天可以再测测

**Comment by TOMhongshu** [comment]
好

**Comment by TOMhongshu** [comment]
我看了一下运行日志 第一次运行也是这样

**Comment by TOMhongshu** [comment]
图片：https://s3.bmp.ovh/imgs/2022/05/14/47eb2f6ae4502a1a.png
这个是夜里定时自动运行的

**Comment by TOMhongshu** [comment]
但是不影响使用 使用都是正常的
